### ISSUE TITLE
Preview mode broken in Next 10.0.2 with target: "serverless": TypeError: e[t] is not a function

### ISSUE THREAD

**Issue by fverloop** [netlify/next-on-netlify#99]
Since we've switched to the latest version of next (10.0.2), [preview mode](https://nextjs.org/docs/advanced-features/preview-mode) has been broken. Everything builds successfully, but when we load our `/api/preview` endpoint we get the following error:

```
[request] /api/preview/
TypeError: e[t] is not a function
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.293 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:29747)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.118 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:28826)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.692 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:17036)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.28 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:15901)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.27 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:3078)
TypeError: e[t] is not a function
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.293 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:29747)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.118 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:28826)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.692 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:17036)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.28 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:15901)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.27 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:3078)
TypeError: e[t] is not a function
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.293 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:29747)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.118 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:28826)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.692 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:17036)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.28 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:15901)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.27 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:3078)
TypeError: e[t] is not a function
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.293 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:29747)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.118 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:28826)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.692 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:17036)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.28 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:15901)
    at __webpack_require__ (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:30130)
    at Object.27 (/Users/florisverloop/Projects/site-sass/site/out_functions/next_api_preview/nextPage.js:43666:3078)

/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^
abort({}) at Error
    at jsStackTrace (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1070:13)
    at stackTrace (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1087:12)
    at process.abort (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:8502:44)
    at process.emit (events.js:310:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

**Comment by FinnWoelm** [comment]
Hi @fverloop,

Thanks for flagging this! I recently tried to switch to Next v10 for our next-on-netlify tests and noticed that all the preview-related tests were indeed failing. From my understanding, this seems to be a bug in Next.js that affects `target: "serverless"`, specifically it happens in the code where Next.js looks for the jsonwebtoken code/module.

You can solve this by switching to `target: "experimental-serverless-trace"` in your `next.config.js`. This setting will somewhat increase your build time, but if that is something you can live with, then it's a good solution. We're working on improving build speed with `experimental-serverless-trace`. 

Difference between the two modes: In serverless-target mode, Next.js inlines all dependencies into a single .js file, leading to smaller file sizes and minimal dependencies, but causing issues with non-JS code (binaries, for example). In experimental-serverless-trace-target mode, Next.js does not inline dependencies and instead uses `require` statements, which works well with binaries, but ends up bundling all dependencies (all of @material-ui, for example, instead of just that one component that you're using). It doesn't affect function speed/performance, but it does require more time for the initial build and upload process.

Do you want to try that and report back? 😊

**Comment by fverloop** [comment]
Thanks for the detailed answer! I've tried switching to `experimental-serverless-trace` but this causes our build to fail because: `Build exceeded maximum allowed runtime`. It now takes more than 30 minutes to build our site. Build time has already gone up significantly (from 5 to 10 minutes) because it needs to generate the preview functions. 10 minutes is long, but we could live with that, 30 minutes is not realistic. 

Is there another simple solution we could explore? FWIW preview mode worked perfectly on `10.0.1`.

**Comment by lqze** [comment]
@FinnWoelm I'm experiencing the same as @fverloop but I can't even get `experimental-serverless-trace` to build on Netlify, its failing when trying to package the functions
```
10:28:27 PM:   2. Functions bundling                                         
10:28:27 PM: ────────────────────────────────────────────────────────────────
10:28:27 PM: ​
10:28:27 PM: Packaging Functions from out_functions directory:
10:28:27 PM:  - next_api_disablepreview/next_api_disablepreview.js
10:28:27 PM:  - next_api_enablepreview/next_api_enablepreview.js
10:28:27 PM:  - next_index/next_index.js
10:28:27 PM:  - next_uri/next_uri.js
10:28:32 PM: ​
10:28:32 PM: ────────────────────────────────────────────────────────────────
10:28:32 PM:   Dependencies installation error                               
10:28:32 PM: ────────────────────────────────────────────────────────────────
10:28:32 PM: ​
10:28:32 PM:   Error message
10:28:32 PM:   A Netlify Function failed to require one of its dependencies.
10:28:32 PM:   If the dependency is a Node module, please make sure it is present in the site's top-level "package.json".
  If it is a local file instead, please make sure the file exists and its filename is correctly spelled.
10:28:32 PM: ​
10:28:32 PM:   In file "/opt/build/repo/out_functions/next_index/next_index.js"
10:28:32 PM:   Cannot find module 'konva'
10:28:32 PM:   Require stack:
10:28:32 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/resolve.js
10:28:32 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/dependencies.js
10:28:32 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/main.js
10:28:32 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins_core/functions/index.js
10:28:32 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/commands/get.js
10:28:32 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/core/main.js
10:28:32 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/core/bin.js
```

I'll raise a separate issue about this..

**Comment by ehmicky** [comment]
@lqze This is probably a separate issue. I think the error message should indicate a way to solve this:

```
Please make sure it is present in the site's top-level "package.json".
```

`konva` should be added to your site's top-level `package.json` (and not a `package.json` in a sub-directory).

**Comment by lqze** [comment]
@ehmicky Yeah this is definitely something funky with Netlify..

It is in my app's root `package.json` now.

After adding it to my app `npm i konva` I'm getting the following.

```
5:10:25 AM: ✅ Success! All done!
5:10:25 AM: ​
5:10:25 AM: (build.command completed in 1m 10.5s)
5:10:25 AM: ​
5:10:25 AM: ────────────────────────────────────────────────────────────────
5:10:25 AM:   2. Functions bundling                                         
5:10:25 AM: ────────────────────────────────────────────────────────────────
5:10:25 AM: ​
5:10:25 AM: Packaging Functions from out_functions directory:
5:10:25 AM:  - next_api_disablepreview/next_api_disablepreview.js
5:10:25 AM:  - next_api_enablepreview/next_api_enablepreview.js
5:10:25 AM:  - next_index/next_index.js
5:10:25 AM:  - next_uri/next_uri.js
5:10:29 AM: ​
5:10:29 AM: ────────────────────────────────────────────────────────────────
5:10:29 AM:   Dependencies installation error                               
5:10:29 AM: ────────────────────────────────────────────────────────────────
5:10:29 AM: ​
5:10:29 AM:   Error message
5:10:29 AM:   A Netlify Function failed to require one of its dependencies.
5:10:29 AM:   If the dependency is a Node module, please make sure it is present in the site's top-level "package.json".
  If it is a local file instead, please make sure the file exists and its filename is correctly spelled.
5:10:29 AM: ​
5:10:29 AM:   In file "/opt/build/repo/out_functions/next_index/next_index.js"
5:10:29 AM:   Cannot find module 'react-native'
5:10:29 AM:   Require stack:
5:10:29 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/resolve.js
5:10:29 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/dependencies.js
5:10:29 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/main.js
5:10:29 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins_core/functions/index.js
5:10:29 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/commands/get.js
5:10:29 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/core/main.js
5:10:29 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/core/bin.js
5:10:29 AM: ​
5:10:29 AM:   Resolved config
5:10:29 AM:   build:
5:10:29 AM:     command: npm run build
```

It's as if it cant resolve any deps or something in the opt folder? Or it's not able to correctly path to it?

**Comment by ehmicky** [comment]
@lqze This issue appears to be separate from the one initially reported by @fverloop.
Would it be possible to create a separate issue, so we don't lose sight on @fverloop's problem. Thanks!

**Comment by lindsaylevine** [comment]
hey all! i'm going to close this issue in favor of https://github.com/netlify/next-on-netlify/issues/120, which groups several `next-on-netlify` issues together related to experimental-serverless-trace. this issue mentions that an improvement has been made to our internal bundling library `zip-it-and-ship-it`, to be released in the new year.

please feel free to re-open this issue if you think #120 does not suffice or if there's a specific piece separate from experimental-serverless-trace that still needs addressing.

**Comment by afzalsayed96** [comment]
@lindsaylevine I understand that #120 addresses all issues with `experimental-serverless-trace`. Are there any plans to make target `serverless` work with Next v10.0.2+?

**Comment by lindsaylevine** [comment]
@afzalsayed96 that is a _very_ good question and need time to think about it.

**Comment by FinnWoelm** [comment]
Hey @afzalsayed96, great point!

This issue is on Next.js' end. We just traced the error down and identified a solution. This has been filed here: https://github.com/vercel/next.js/issues/20575 (in case you're curious about the details 😊).

I'm reopening this issue, so we can track progress on the issue in the next.js repo.

Note that there are currently three possible work-arounds, which I'm happy to expand on, if you'd like:
1. Using `target: "experimental-serverless-trace"`
2. Downgrading to Next v10.0.1
3. Using `patch-package` to replace the two instances of `next/dist/compiled/jsonwebtoken` with `jsonwebtoken` in https://github.com/vercel/next.js/blob/master/packages/next/next-server/server/api-utils.ts ([patch here](https://gist.github.com/FinnWoelm/6109fdc123f293745c3424e42b260989)) and installing `jsonwebtoken` as a dependency with `npm install jsonwebtoken@3.5.1`.

**Comment by lindsaylevine** [comment]
according to @FinnWoelm , this will be resolved in the next release of Next!!! :)

**Comment by lindsaylevine** [comment]
next 10.0.6 is out! i just confirmed this works with next 10.0.6 and latest next-on-netlify for both targets (serverless and experimental-serverless-trace). please comment if you happen to still being have issues! <3
