### ISSUE TITLE
Cannot find module critters

### ISSUE THREAD

**Issue by mannycolon** [netlify/next-on-netlify#157]
- See https://app.netlify.com/sites/silly-golick-1b4f9b/deploys/6009e6bf6ff93b00084d588f

- netlify.toml
```
[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"
```

- 

![Screen Shot 2021-01-21 at 3 47 42 PM](https://user-images.githubusercontent.com/17072300/105410535-11018600-5c00-11eb-83a1-f8fe67d44609.png)
![Screen Shot 2021-01-21 at 3 48 27 PM](https://user-images.githubusercontent.com/17072300/105410592-28d90a00-5c00-11eb-9e67-4d138e1e59c9.png)

**Comment by neefrehman** [comment]
@lindsaylevine heya! continuing on from https://github.com/netlify/next-on-netlify/issues/103.

>ah wait just realized you're using the CLI (i think)

I'm not using the CLI, just the github continuous integration.

here's the deploy link: https://app.netlify.com/teams/neef/builds/600d76a5b2138f000738f5dd

**Comment by ezekielaquino** [comment]
I'm also having this error! Occurred when I updated `next` to 10.0.5 and `next-on-netlify` to latest

**Comment by erezrokah** [comment]
Hi everyone, sorry for the delay to respond. @mannycolon I forked you repo and updated to `next@10.0.5` and my build is passing. See https://github.com/erezrokah/next-prankz/commit/682f13dffe5350ea30d727b81285991f9b5aeac9 and https://app.netlify.com/sites/objective-cori-263efa/deploys/600f019de7f59c000714301b. Can you provide a **step by step** guide to reproduce the error?

For @neefrehman and @ezekielaquino can you share a public repo I can use to reproduce this?

**Comment by neefrehman** [comment]
@erezrokah here you go: https://github.com/neefrehman/allergies.travel/tree/staging. Note that the bug is only on the staging branch, as main still uses `next export`

**Comment by mannycolon** [comment]
@erezrokah It started working after your changes on https://github.com/netlify/build/issues/2193

**Comment by erezrokah** [comment]
> @erezrokah here you go: https://github.com/neefrehman/allergies.travel/tree/staging. Note that the bug is only on the staging branch, as main still uses `next export`

Thanks @neefrehman that helps. I was able to reproduce the issue and will submit a fix soon.
As a workaround you can change this line:
https://github.com/neefrehman/allergies.travel/blob/f06dd33785de8125bfff15d275bb534e99319598/package.json#L36
to `"next": "^10.0.0",`

**Comment by erezrokah** [comment]
FYI, we haven't released the fix to our production env yet - I'll follow up here once it's released

**Comment by erezrokah** [comment]
This fixed was rolled out to our production environment. Please comment if the issue still persists

**Comment by jhesgodi** [comment]
@erezrokah thanks for putting time on the fixes. I think there could be another use case missing as of today I found the error again.
Please find:
* a base repo using `NoN` here:
https://github.com/jhesg/netlify-next

* netlify public logs:
  * it fails for latest nextjs at branch **[spike/with-latest-nextjs](https://github.com/jhesg/netlify-next/tree/spike/with-latest-nextjs)**
https://app.netlify.com/sites/competent-edison-b01f20/deploys/60138bb2a886f500087d469a

  * succeed if by using workaround to set next  to `^10.0.0` at branch **[master](https://github.com/jhesg/netlify-next/tree/master)**
  https://app.netlify.com/sites/competent-edison-b01f20/deploys/601389ccbd57bb4a396f0d3c

**Comment by lindsaylevine** [comment]
@jhesgodi

**Comment by erezrokah** [comment]
Thanks for reporting @jhesgodi - this is indeed a use case we didn't consider.
Our current logic looks as `next` version but won't match `latest`:
https://github.com/netlify/zip-it-and-ship-it/blob/c17440c2a14c35521cb123c51516d4d86645204e/src/node_dependencies/nested.js#L81

We're discussing on a [long term solution](https://github.com/netlify/zip-it-and-ship-it/issues/225) so plugins can customize our bundling logic.
